/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import javax.swing.DefaultListModel;

/**
 *
 * @author onur
 */
public class FrmServer extends javax.swing.JFrame {
    Server myserver;
    public static DefaultListModel clientMessagesModel;

    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
        this.myserver = new Server(5000);
        clientMessagesModel= new DefaultListModel();
        lst_clientMessages.setModel(clientMessagesModel);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_port = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_clientMessages = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_message = new javax.swing.JTextArea();
        btn_sendBroadcast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_port.setText("5000");
        getContentPane().add(txt_port, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 60, -1));

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, -1));

        jScrollPane1.setViewportView(lst_clientMessages);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 170, 200));

        txta_message.setColumns(20);
        txta_message.setRows(5);
        jScrollPane2.setViewportView(txta_message);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btn_sendBroadcast.setText("Broadcast Message");
        btn_sendBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendBroadcastActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sendBroadcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        this.myserver.Listen();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_sendBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendBroadcastActionPerformed
        // TODO add your handling code here:
        this.myserver.SendBroadcastMessage(txta_message.getText());
    }//GEN-LAST:event_btn_sendBroadcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendBroadcast;
    private javax.swing.JButton btn_start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_clientMessages;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextArea txta_message;
    // End of variables declaration//GEN-END:variables
}
